### ISSUE TITLE
`get_optics` is broken

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-junos#104]
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
>>> j.get_optics()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/state/home/mircea/napalm/local/lib/python2.7/site-packages/napalm_junos/junos.py", line 1421, in get_optics
    if optics['input_power'] != '- Inf'
TypeError: float() argument must be a string or a number
```

### napalm-junos version
(Paste verbatim output from `pip freeze | grep napalm-junos` between quotes below)

```
0.6.0
```

### JunOS version
(Paste verbatim output from `show version and haiku` between quotes below)

```
14.2R6.5
```

**Comment by mirceaulinic** [comment]
Same on `13.3R6.5`

**Comment by pkleanthous-zz** [comment]
Tested it with 
```
napalm-junos==0.6.0
```
```
root> show version and haiku    
Model: vsrx
Junos: 15.1X49-D60.7
JUNOS Software Release [15.1X49-D60.7]


        Another day dies
        More joy than I can fathom
        Yet more tomorrow
```

It returns an empty dict

```python
In [9]: print device.get_optics()
{}
```

**Comment by mirceaulinic** [comment]
Yeah... this might be because a vSRX does not have any physical interfaces :)
