### ISSUE TITLE
KeyError: u'peer_fwd_rti' on Junos 15

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-junos#191]
### Description of Issue/Question

Apparently, the `peer_fwd_rti` is still not widely available on all Junos >= 15 distributions.

### napalm-junos version
(Paste verbatim output from `pip freeze | grep napalm-junos` between quotes below)

```
0.11.0
```

### JunOS version
(Paste verbatim output from `show version and haiku` between quotes below)

```
15.1F7.3
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```python
>>> j.get_bgp_neighbors()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm_junos/junos.py", line 577, in get_bgp_neighbors
    _get_bgp_neighbors_core(instance_neighbors)
  File "/usr/local/lib/python2.7/dist-packages/napalm_junos/junos.py", line 528, in _get_bgp_neighbors_core
    peer_fwd_rti = neighbor_details.pop('peer_fwd_rti')
KeyError: u'peer_fwd_rti
```

**Comment by mirceaulinic** [comment]
Solved in https://github.com/napalm-automation/napalm-junos/pull/193
