### ISSUE TITLE
Cannot close and reopen session

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-junos#29]
### Description of Issue/Question

Cannot close and reopen session with a device because the config object `cu` is already binded.
### napalm-junos version

```
napalm-junos==0.2.1
```
### JunOS version

```
any
```
### Steps to Reproduce the Issue
- Open connection with the device
- Close the conection
- Open it again
### Error Traceback

```
>>> j.open()
>>> j.close()
>>> j.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/state/home/mircea/napalm-junos/napalm_junos/junos.py", line 73, in open
    self.device.bind(cu=Config)
  File "/state/home/mircea/napalm-test/local/lib/python2.7/site-packages/junos_eznc-1.3.1-py2.7.egg/jnpr/junos/device.py", line 756, in bind
    name)
ValueError: requested attribute name cu already exists
```
### Solution

Must remove the binding during `close`.

**Comment by mirceaulinic** [comment]
Solved via https://github.com/napalm-automation/napalm-junos/pull/30
