### ISSUE TITLE
Unable to retrieve BGP config from JunOS < 13

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-junos#59]
### Description of Issue/Question

Unable to retrieve BGP config from vSRX
### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [x] Yes
- [ ] No
### Setup

Using the old vSRX box running 12.1, tried to retrieve the BGP config. 
### napalm-junos version

0.3.0
### JunOS version

(Paste verbatim output from `show version and haiku` between quotes below)

```
root@vsrx2> show version and haiku
Hostname: vsrx2
Model: firefly-perimeter
JUNOS Software Release [12.1X47-D20.7]


        Just like mosquitoes
        Bugs pepper all my source code
        Keeps me off the streets
```
### Steps to Reproduce the Issue

Just a minimal config for BGP is enough to reproduce:

```
root@vsrx2> show configuration protocols bgp | display set
set protocols bgp group TEST type external
set protocols bgp group TEST peer-as 1234
set protocols bgp group TEST neighbor 1.2.3.4
```

```
root@vsrx2> show configuration protocols bgp | display xml
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/12.1X47/junos">
    <configuration junos:commit-seconds="1476138575" junos:commit-localtime="2016-10-10 22:29:35 UTC" junos:commit-user="root">
            <protocols>
                <bgp>
                    <group>
                        <name>TEST</name>
                        <type>external</type>
                        <peer-as>1234</peer-as>
                        <neighbor>
                            <name>1.2.3.4</name>
                        </neighbor>
                    </group>
                </bgp>
            </protocols>
    </configuration>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>
```

Then open the connection using NAPALM and execute `get_bgp_config()`
### Error Traceback

(Paste the complete traceback of the exception between quotes below)

```
>>> e.get_bgp_config()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mirucha/cfnapalm/lib/python2.7/site-packages/napalm_junos/junos.py", line 598, in get_bgp_config
    peers.get()  # unfortunately cannot add filters for group name of neighbor address
  File "/Users/mirucha/cfnapalm/lib/python2.7/site-packages/jnpr/junos/factory/cfgtable.py", line 546, in get
    self.xml = self.RPC.get_config(get_cmd, options=options)
  File "/Users/mirucha/cfnapalm/lib/python2.7/site-packages/jnpr/junos/rpcmeta.py", line 52, in get_config
    return self._junos.execute(rpc)
  File "/Users/mirucha/cfnapalm/lib/python2.7/site-packages/jnpr/junos/decorators.py", line 71, in wrapper
    return function(*args, **kwargs)
  File "/Users/mirucha/cfnapalm/lib/python2.7/site-packages/jnpr/junos/decorators.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/Users/mirucha/cfnapalm/lib/python2.7/site-packages/jnpr/junos/device.py", line 529, in execute
    raise e(cmd=rpc_cmd_e, rsp=rsp, errs=err)
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: neighbor, message: syntax error)
```

**Comment by mirceaulinic** [comment]
Oups, this seems to be related to JunOS 12 😞

**Comment by mirceaulinic** [comment]
Tested against other devices - looks like older versions are not able to filter the XML tree properly although the structure is the same.
This will need more changes - basically the whole architecture of `get_bgp_config` must be changed.
