### ISSUE TITLE
Not able get static routes

### ISSUE THREAD

**Issue by piter50** [napalm-automation/napalm-junos#74]
### Description of Issue/Question
When using salt-stack to grab a static route from a junos router, I get an error about it being a NoneType

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [x] Yes
- [ ] No

### napalm-junos version
(Paste verbatim output from `pip freeze | grep napalm-junos` between quotes below)

```
napalm-junos==0.4.3
```

### JunOS version
(Paste verbatim output from `show version and haiku` between quotes below)

```
Hostname: myrouter
Model: mx5-t
Junos: 13.3R6.5
JUNOS Base OS boot [13.3R6.5]
JUNOS Base OS Software Suite [13.3R6.5]
JUNOS Kernel Software Suite [13.3R6.5]
JUNOS Crypto Software Suite [13.3R6.5]
JUNOS Packet Forwarding Engine Support (MX80) [13.3R6.5]
JUNOS Online Documentation [13.3R6.5]
JUNOS Services Application Level Gateways [13.3R6.5]
JUNOS Services Jflow Container package [13.3R6.5]
JUNOS Services Stateful Firewall [13.3R6.5]
JUNOS Services NAT [13.3R6.5]
JUNOS Services RPM [13.3R6.5]
JUNOS Services Crypto [13.3R6.5]
JUNOS Services SSL [13.3R6.5]
JUNOS Services IPSec [13.3R6.5]
JUNOS Routing Software Suite [13.3R6.5]


        Help me, Obi-Wan
        I just saw Episode Two
        You're my only hope
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
salt myrouter route.show 10.0.0.0/8 static
myrouter:
    ----------
    comment:
        Cannot execute "get_route_to" on myrouter as user. Reason: argument of type 'NoneType' is not iterable!
    out:
        ----------
    result:
        False
    traceback:
        Traceback (most recent call last):
          File "/var/cache/salt/minion/extmods/proxy/napalm.py", line 284, in call
            out = getattr(NETWORK_DEVICE.get('DRIVER'), method)(**params)  # calls the method with the specified parameters
          File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/napalm_junos/junos.py", line 1061, in get_route_to
            key: value for key, value in all_protocol_attributes.iteritems()
          File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/napalm_junos/junos.py", line 1062, in <dictcomp>
            if key in _PROTOCOL_SPECIFIC_FIELDS_.get(protocol)
        TypeError: argument of type 'NoneType' is not iterable
```

```
Here are the statics configured on the routers default instance
user@myrouter> show configuration routing-options
static {
    route 10.0.0.0/8 next-hop 192.168.1.1;
    route 192.168.0.0/16 next-hop 192.168.1.1;
    route 172.16.0.0/12 next-hop 192.168.1.1;
}
```

**Comment by mirceaulinic** [comment]
A stupid bug... :(

`_PROTOCOL_SPECIFIC_FIELDS_` should have one more key `static` having `[]` as value.

**Comment by piter50** [comment]
```
            ],
            'static' : []
      }
```

Added that in and restarted the salt-proxy for that juniper and can confirm it returned the routes I expected to see
